version: 2.1
orbs:
  scheduled-pipelines: brivu/scheduled-pipelines@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.5

filters: &filters
  tags:
    only: /.*/

workflows:
  test-deploy:
    jobs:
      - scheduled-pipelines/update-schedules:
          name: integration-test
          pre-steps:
            - checkout
            - scheduled-pipelines/update-schedules:
                schedule-path: "./sample/initial-schedules.json"
          executor: linux
          schedule-path: "./sample/updated-schedules.json"
          post-steps:
            - scheduled-pipelines/delete-schedule:
                schedule-name: Test4
            - scheduled-pipelines/delete-schedule:
                schedule-name: Test5
            - scheduled-pipelines/delete-schedule:
                schedule-name: Test6
            - run:
                name: Verifying deletion of all schedules.
                command: |
                  if [ -z $(jq -c '.items[]' current_schedules.json) ]; then 
                    exit 0
                  else
                    echo "All schedules should be deleted. Please recheck jobs"
                    exit 1
                  fi

          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: brivu/scheduled-pipelines
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            - integration-test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
executors:
  linux:
    docker:
      - image: cimg/base:current

